#!/bin/sh

encodeURIComponent() {
  awk 'BEGIN {while (y++ < 125) z[sprintf("%c", y)] = y
  while (y = substr(ARGV[1], ++j, 1))
  q = y ~ /[[:alnum:]_.!~*\47()-]/ ? q y : q sprintf("%%%02X", z[y])
  print q}' "$1"
}

if [ -z "$@" ]; then
  xdg-open http://google.com
else
  xdg-open http://google.com/search?q=$(encodeURIComponent "$@")
fi
