#!/bin/bash

printf '     '
for bg in $( seq 40 47 ) ; do
	printf '    %02dm ' "$bg"
done
printf '\n\n'

for fg in $( seq 30 37 ) ; do
	printf " %02dm " "$fg"
	printf '\033[%dm' "$fg"
	for bg in $( seq 40 47 ) ; do
		printf '  \033[%dm quux \033[40m' "$bg"
	done
	printf '\033[0m\n'
done

for fg in $( seq 30 37 ) ; do
	printf " %02dm " "$fg"
	printf '\033[%dm' "$fg"
	for bg in $( seq 40 47 ) ; do
		printf '  \033[1;%dm quux \033[40m' "$bg"
	done
	printf '\033[0m\n'
done
